document.write('<link rel="stylesheet" type="text/css" href="../../lib/ext/resources/css/ext-all.css">');
document.write('<script type="text/javascript" src="../../lib/ext/adapter/ext/ext-base.js"></script>');
document.write('<script type="text/javascript" src="../../lib/ext/ext-all.js"></script>');
document.write('<script type="text/javascript" src="../../lib/ext/source/locale/ext-lang-zh_CN_gb.js"></script>');
document.write('<script type="text/javascript" src="../../seam/resource/remoting/resource/remote.js"></script>');
document.write('<script type="text/javascript" src="../../js/base/gridData.js"></script>');
document.write('<script type="text/javascript" src="../../js/base/MyGrid.js"></script>');
document.write('<script type="text/javascript" src="../../js/base/departmentUser.js"></script>');
document.write('<script type="text/javascript" src="../../js/base/roleListSelect.js"></script>');
document.write('<script type="text/javascript" src="../../js/base/tlework.js"></script>');
