package com.sysware.customize.hd.investment.purchaseRequest.PEsummary.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbSpecialprojectdetails generated by MyEclipse Persistence Tools
 */

@Entity
@Table(name = "TB_SPECIALPROJECTDETAILS")
public class SpecialProjectDetails implements java.io.Serializable {

	// Fields
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(generator="myGuidGenerator")
	@GenericGenerator(name="myGuidGenerator",strategy="com.sysware.util.MyHibernateGuidGenerator")
	private String id;
	
	@ManyToOne(fetch=FetchType.EAGER,optional=true,cascade=CascadeType.REFRESH)
	@JoinColumn(name="SPECIALPROJECTID")
	private SpecialProject specialproject;
	
	@Column(name = "EQUIPNAME")
	private String equipname;//设备名称
	
	@Column(name = "TECHNICALDEPTHEAD")
	private String technicaldepthead;//技改部负责人
	
	@Column(name = "USEDEPTHEAD")
	private String usedepthead;//使用部门负责人
	
	@Column(name = "MAINTECHNICALINDEX")
	private String maintechnicalindex;//主要技术指标
	
	@Column(name = "MANUFACTURE")
	private String manufacture;//参考厂商或国别
	
	@Column(name = "NUMS")
	private String nums;//数量台/套
	
	@Column(name = "REPLYPRICE")
	private BigDecimal replyprice;//批复价格
	
	@Column(name = "REPLYBIDDING")
	private String replybidding;//批复招标方式
	
	@Column(name = "INVESTIGATIONTIME")
	private Date investigationtime;//调研/选型完成日期
	
	@Column(name = "BIDDINGTIME")
	private Date biddingtime;//招标完成日期
	
	@Column(name = "CONTRACTTIME")
	private Date contracttime;//签订合同日期
	
	@Column(name = "CONTRACTMONEY")
	private BigDecimal contractmoney;//合同金额
	
	@Column(name = "PAYMENT")
	private BigDecimal payment;//已付款金额
	
	@Column(name = "SETTLEMENT")
	private BigDecimal settlement;//已结算金额
	
	@Column(name = "ANNUALADVANCE")
	private BigDecimal annualadvance;//本年预计付款金额
	
	@Column(name = "ANNUALSETTLEMENT")
	private BigDecimal annualsettlement;//本年预计结算金额
	
	@Column(name = "PREACCEPTANCE")
	private String preacceptance;//预计验收交付
	
	@Column(name = "CREATETIME")
	private Date createtime;//创建时间
	
	@Column(name = "REMARK")
	private String remark;//备注

	// Constructors

	/** default constructor */
	public SpecialProjectDetails() {
	}

	/** minimal constructor */
	public SpecialProjectDetails(String id, SpecialProject specialproject) {
		this.id = id;
		this.specialproject = specialproject;
	}

	/** full constructor */
	public SpecialProjectDetails(String id, SpecialProject specialproject,
			String equipname, String technicaldepthead, String usedepthead,
			String maintechnicalindex, String manufacture, String nums,
			BigDecimal replyprice, String replybidding, Date investigationtime,
			Date biddingtime, Date contracttime, BigDecimal contractmoney,
			BigDecimal payment, BigDecimal settlement, BigDecimal annualadvance,
			BigDecimal annualsettlement, String preacceptance, Date createtime,
			String remark) {
		this.id = id;
		this.specialproject = specialproject;
		this.equipname = equipname;
		this.technicaldepthead = technicaldepthead;
		this.usedepthead = usedepthead;
		this.maintechnicalindex = maintechnicalindex;
		this.manufacture = manufacture;
		this.nums = nums;
		this.replyprice = replyprice;
		this.replybidding = replybidding;
		this.investigationtime = investigationtime;
		this.biddingtime = biddingtime;
		this.contracttime = contracttime;
		this.contractmoney = contractmoney;
		this.payment = payment;
		this.settlement = settlement;
		this.annualadvance = annualadvance;
		this.annualsettlement = annualsettlement;
		this.preacceptance = preacceptance;
		this.createtime = createtime;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SpecialProject getSpecialproject() {
		return this.specialproject;
	}

	public void setSpecialproject(SpecialProject specialproject) {
		this.specialproject = specialproject;
	}

	public String getEquipname() {
		return this.equipname;
	}

	public void setEquipname(String equipname) {
		this.equipname = equipname;
	}

	public String getTechnicaldepthead() {
		return this.technicaldepthead;
	}

	public void setTechnicaldepthead(String technicaldepthead) {
		this.technicaldepthead = technicaldepthead;
	}

	public String getUsedepthead() {
		return this.usedepthead;
	}

	public void setUsedepthead(String usedepthead) {
		this.usedepthead = usedepthead;
	}

	public String getMaintechnicalindex() {
		return this.maintechnicalindex;
	}

	public void setMaintechnicalindex(String maintechnicalindex) {
		this.maintechnicalindex = maintechnicalindex;
	}

	public String getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	public String getNums() {
		return this.nums;
	}

	public void setNums(String nums) {
		this.nums = nums;
	}

	public BigDecimal getReplyprice() {
		return this.replyprice;
	}

	public void setReplyprice(BigDecimal replyprice) {
		this.replyprice = replyprice;
	}

	public String getReplybidding() {
		return this.replybidding;
	}

	public void setReplybidding(String replybidding) {
		this.replybidding = replybidding;
	}

	public Date getInvestigationtime() {
		return this.investigationtime;
	}

	public void setInvestigationtime(Date investigationtime) {
		this.investigationtime = investigationtime;
	}

	public Date getBiddingtime() {
		return this.biddingtime;
	}

	public void setBiddingtime(Date biddingtime) {
		this.biddingtime = biddingtime;
	}

	public Date getContracttime() {
		return this.contracttime;
	}

	public void setContracttime(Date contracttime) {
		this.contracttime = contracttime;
	}

	public BigDecimal getContractmoney() {
		return this.contractmoney;
	}

	public void setContractmoney(BigDecimal contractmoney) {
		this.contractmoney = contractmoney;
	}

	public BigDecimal getPayment() {
		return this.payment;
	}

	public void setPayment(BigDecimal payment) {
		this.payment = payment;
	}

	public BigDecimal getSettlement() {
		return this.settlement;
	}

	public void setSettlement(BigDecimal settlement) {
		this.settlement = settlement;
	}

	public BigDecimal getAnnualadvance() {
		return this.annualadvance;
	}

	public void setAnnualadvance(BigDecimal annualadvance) {
		this.annualadvance = annualadvance;
	}

	public BigDecimal getAnnualsettlement() {
		return this.annualsettlement;
	}

	public void setAnnualsettlement(BigDecimal annualsettlement) {
		this.annualsettlement = annualsettlement;
	}

	public String getPreacceptance() {
		return this.preacceptance;
	}

	public void setPreacceptance(String preacceptance) {
		this.preacceptance = preacceptance;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}