package com.sysware.customize.hd.investment.purchaseRequest.PEsummary.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
/**
 * TbSpecialproject generated by MyEclipse Persistence Tools
 */

@Entity
@Table(name = "TB_SPECIALPROJECT")
public class SpecialProject implements java.io.Serializable {

	// Fields
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(generator="myGuidGenerator")
	@GenericGenerator(name="myGuidGenerator",strategy="com.sysware.util.MyHibernateGuidGenerator")
	private String id;
	
	@Column(name = "PROJECTNAME")
	private String projectname;//项目名称
	
	@Column(name = "PROJECTNUM")
	private String projectnum;//项目编号
	
	@Column(name = "CREATEPERSON")
	private String createperson;//创建者
	
	@Column(name = "CREATETIME")
	private Date createtime;//创建时间
	
	@Column(name = "APPROVALSTATE")
	private Long approvalstate;//审批状态
	
	@Column(name = "APPROVALTIME")
	private Date approvaltime;//审批时间
	
	@Column(name = "CONTRACTMONEY")
	private BigDecimal contractmoney;//合同金额
	
	@Column(name = "REMARK")
	private String remark;	//备注
	
	@OneToMany(mappedBy="specialproject",fetch=FetchType.LAZY,cascade = { CascadeType.REMOVE })
	private Set<SpecialProjectDetails> specialprojectdetails = new HashSet<SpecialProjectDetails>();
	

	// Constructors

	/** default constructor */
	public SpecialProject() {
	}

	/** minimal constructor */
	public SpecialProject(String id, String projectname, String createperson,
			Date createtime, Long approvalstate) {
		this.id = id;
		this.projectname = projectname;
		this.createperson = createperson;
		this.createtime = createtime;
		this.approvalstate = approvalstate;
	}

	/** full constructor */
	public SpecialProject(String id, String projectname, String createperson,
			Date createtime, Long approvalstate, Date approvaltime,
			String remark) {
		this.id = id;
		this.projectname = projectname;
		this.createperson = createperson;
		this.createtime = createtime;
		this.approvalstate = approvalstate;
		this.approvaltime = approvaltime;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	public String getCreateperson() {
		return this.createperson;
	}

	public void setCreateperson(String createperson) {
		this.createperson = createperson;
	}

	public String getProjectnum() {
		return projectnum;
	}

	public void setProjectnum(String projectnum) {
		this.projectnum = projectnum;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Long getApprovalstate() {
		return this.approvalstate;
	}

	public void setApprovalstate(Long approvalstate) {
		this.approvalstate = approvalstate;
	}

	public Date getApprovaltime() {
		return this.approvaltime;
	}

	public void setApprovaltime(Date approvaltime) {
		this.approvaltime = approvaltime;
	}
	public BigDecimal getContractmoney() {
		return contractmoney;
	}

	public void setContractmoney(BigDecimal contractmoney) {
		this.contractmoney = contractmoney;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<SpecialProjectDetails> getSpecialprojectdetails() {
		return specialprojectdetails;
	}

	public void setSpecialprojectdetails(
			Set<SpecialProjectDetails> specialprojectdetails) {
		this.specialprojectdetails = specialprojectdetails;
	}

}